import { useState } from "react";

import jsPDF from "jspdf";

import { signOut } from "firebase/auth";

import { auth, db } from "../firebase";

import {
  PieChart,
  Pie,
  Cell,
  Tooltip,
  Legend
} from "recharts";

import {
  addDoc,
  collection
} from "firebase/firestore";

function Dashboard() {

  const [transport, setTransport] = useState("");
  const [electricity, setElectricity] = useState("");
  const [food, setFood] = useState("");

  const [darkMode, setDarkMode] = useState(true);

  // TOTAL

  const total =
    Number(transport || 0) +
    Number(electricity || 0) +
    Number(food || 0);

  // CHART DATA

  const data = [
    {
      name: "Transport",
      value: Number(transport || 0)
    },
    {
      name: "Electricity",
      value: Number(electricity || 0)
    },
    {
      name: "Food",
      value: Number(food || 0)
    }
  ];

  const COLORS = [
    "#22c55e",
    "#3b82f6",
    "#f97316"
  ];

  // ECO STATUS

  let grade = "🌱 Excellent";
  let badge = "🌱 Eco Hero";
  let achievement = "🌱 Eco Warrior";
  let specialReward = "";

  if (total < 100) {

    specialReward = "🥇 Top Eco Performer";

  }

  if (total > 300) {

    grade = "⚠️ High Emission";
    badge = "⚠️ Pollution Alert";
    achievement = "⚠️ Needs Improvement";

  } else if (total > 150) {

    grade = "🌍 Moderate";
    badge = "🌍 Eco Supporter";
    achievement = "🌍 Green Supporter";

  }

  // PDF DOWNLOAD

  const downloadPDF = () => {

    const doc = new jsPDF();

    doc.setFillColor(204, 232, 207);

    doc.rect(0, 0, 210, 297, "F");

    doc.setFontSize(24);

    doc.setTextColor(0, 128, 0);

    doc.text(
      "Eco Carbon Footprint Report",
      20,
      20
    );

    doc.setDrawColor(34, 197, 94);

    doc.line(20, 28, 190, 28);

    doc.setFontSize(18);

    doc.setTextColor(0, 0, 0);

    doc.text("Carbon Details", 20, 45);

    doc.setFontSize(15);

    doc.text(
      `Transport Value: ${transport || 0}`,
      25,
      65
    );

    doc.text(
      `Electricity Value: ${electricity || 0}`,
      25,
      85
    );

    doc.text(
      `Food Value: ${food || 0}`,
      25,
      105
    );

    doc.setFontSize(18);

    doc.setTextColor(220, 38, 38);

    doc.text(
      `Total CO2 Score: ${total}`,
      20,
      135
    );

    doc.setFontSize(16);

    doc.setTextColor(0, 0, 0);

    doc.text(
      `Achievement Badge: ${badge}`,
      20,
      160
    );

    const today = new Date();

    doc.setFontSize(12);

    doc.text(
      `Generated on: ${today.toLocaleString()}`,
      20,
      190
    );

    doc.setTextColor(100);

    doc.text(
      "Generated by Eco Carbon Tracker",
      20,
      270
    );

    doc.save("Eco_Report.pdf");

  };

  // SAVE REPORT

  const saveReport = async () => {

    try {

      await addDoc(
        collection(db, "reports"),
        {
          userId: auth.currentUser.uid,
          
          transport,
          electricity,
          food,
          total,
          createdAt: new Date()
        }
      );

      alert("Report Saved Successfully 🔥");

      setTransport("");
      setElectricity("");
      setFood("");

    } catch (error) {

      alert(error.message);

    }

  };

  // LOGOUT

  const handleLogout = async () => {

    await signOut(auth);

  };

  return (

    <div
      className={`min-h-screen p-8 transition-all duration-500 ${
        darkMode
          ? "bg-slate-900 text-white"
          : "bg-gray-100 text-black"
      }`}
    >

      {/* HEADING */}

      <h1
        className={`text-5xl font-bold text-center mb-10 ${
          darkMode
            ? "text-green-400"
            : "text-green-800"
        }`}
      >
        🌍 Carbon Footprint Dashboard
      </h1>

      {/* NAVIGATION */}

      <div className="flex justify-center gap-4 mb-8">

        <a
          href="/dashboard"
          className="bg-green-500 px-6 py-3 rounded-xl font-bold text-white"
        >
          🌍 Dashboard
        </a>

        <a
          href="/history"
          className="bg-blue-500 px-6 py-3 rounded-xl font-bold text-white"
        >
          📜 History
        </a>

        <button
          onClick={handleLogout}
          className="bg-red-500 px-6 py-3 rounded-xl font-bold text-white hover:bg-red-600"
        >
          🚪 Logout
        </button>

      </div>

      {/* DARK MODE */}

      <div className="flex justify-center mb-8">

        <button
          onClick={() =>
            setDarkMode(!darkMode)
          }
          className="bg-green-500 px-6 py-3 rounded-xl font-bold hover:bg-green-600"
        >
          {darkMode
            ? "☀️ Light Mode"
            : "🌙 Dark Mode"}
        </button>

      </div>

      {/* INPUTS */}

      <div className="grid md:grid-cols-3 gap-6">

        {/* TRANSPORT */}

        <div
          className={`p-6 rounded-2xl shadow-lg ${
            darkMode
              ? "bg-slate-800"
              : "bg-white"
          }`}
        >

          <h2 className="text-2xl mb-4 text-green-400">
            🚗 Transport
          </h2>

          <input
            type="number"
            placeholder="KM traveled"
            value={transport}
            onChange={(e) =>
              setTransport(e.target.value)
            }
            className="w-full p-3 rounded-lg bg-slate-700 text-white"
          />

        </div>

        {/* ELECTRICITY */}

        <div
          className={`p-6 rounded-2xl shadow-lg ${
            darkMode
              ? "bg-slate-800"
              : "bg-white"
          }`}
        >

          <h2 className="text-2xl mb-4 text-green-400">
            ⚡ Electricity
          </h2>

          <input
            type="number"
            placeholder="Units consumed"
            value={electricity}
            onChange={(e) =>
              setElectricity(e.target.value)
            }
            className="w-full p-3 rounded-lg bg-slate-700 text-white"
          />

        </div>

        {/* FOOD */}

        <div
          className={`p-6 rounded-2xl shadow-lg ${
            darkMode
              ? "bg-slate-800"
              : "bg-white"
          }`}
        >

          <h2 className="text-2xl mb-4 text-green-400">
            🍔 Food
          </h2>

          <input
            type="number"
            placeholder="Meals count"
            value={food}
            onChange={(e) =>
              setFood(e.target.value)
            }
            className="w-full p-3 rounded-lg bg-slate-700 text-white"
          />

        </div>

      </div>

      {/* RESULT */}

      <div className="bg-green-500 mt-10 p-10 rounded-2xl text-center shadow-2xl">

        <h2 className="text-4xl font-bold mb-4">
          Total Carbon Score
        </h2>

        <p className="text-6xl font-bold mb-4">
          {total} CO₂
        </p>

        <p className="text-2xl font-bold">
          {grade}
        </p>

        <p className="mt-4 text-xl font-semibold">
          🌳 Trees Needed to Offset:
          {" "}
          {Math.ceil(total / 10)}
        </p>

        <p className="mt-4 text-2xl font-bold">
          🏆 Badge: {badge}
        </p>

        <p className="mt-4 text-xl font-semibold">
          🎖 Achievement: {achievement}
        </p>

        {specialReward && (

          <p className="mt-4 text-2xl font-bold text-yellow-300">
            {specialReward}
          </p>

        )}

        {/* PROGRESS BAR */}

        <div className="mt-6">

          <p className="text-xl font-bold mb-2">
            Carbon Impact Level
          </p>

          <div className="w-full bg-slate-300 rounded-full h-6">

            <div
              className={`h-6 rounded-full ${
                total > 300
                  ? "bg-red-600"
                  : total > 150
                  ? "bg-yellow-500"
                  : "bg-green-700"
              }`}
              style={{
                width: `${Math.min(total, 100)}%`
              }}
            ></div>

          </div>

        </div>

        {/* BUTTONS */}

        <div className="flex gap-4 justify-center mt-6">

          <button
            onClick={saveReport}
            className="bg-slate-900 px-6 py-3 rounded-xl text-white font-bold"
          >
            Save Report ☁️
          </button>

          <button
            onClick={downloadPDF}
            className="bg-blue-600 px-6 py-3 rounded-xl text-white font-bold"
          >
            Download PDF 📥
          </button>

        </div>

      </div>

      {/* RECOMMENDATIONS */}

      <div
        className={`mt-10 p-8 rounded-2xl ${
          darkMode
            ? "bg-slate-800"
            : "bg-green-50"
        }`}
      >

        <h2 className="text-3xl mb-6 text-green-400">
          💡 Smart Eco Recommendations
        </h2>

        <ul className="space-y-4 text-lg">

          {transport > 100 && (
            <li>
              🚲 Use public transport or cycling.
            </li>
          )}

          {electricity > 100 && (
            <li>
              💡 Reduce electricity usage.
            </li>
          )}

          {food > 50 && (
            <li>
              🥗 Reduce food waste.
            </li>
          )}

          {total < 150 && (
            <li>
              🌱 Great job! Low carbon footprint.
            </li>
          )}

        </ul>

      </div>

      {/* CHART */}

      <div
        className={`mt-10 p-8 rounded-2xl ${
          darkMode
            ? "bg-slate-800"
            : "bg-blue-50"
        }`}
      >

        <h2 className="text-3xl mb-6 text-center text-green-400">
          📊 Emission Analytics
        </h2>

        <div className="flex justify-center">

          <PieChart width={400} height={400}>

            <Pie
              data={data}
              cx="50%"
              cy="50%"
              outerRadius={120}
              dataKey="value"
              label
            >

              {data.map((entry, index) => (

                <Cell
                  key={index}
                  fill={COLORS[index]}
                />

              ))}

            </Pie>

            <Tooltip />

            <Legend />

          </PieChart>

        </div>

      </div>

      {/* SDG */}

      <div className="mt-10">

        <h2 className="text-3xl mb-6 text-green-400">
          🎯 Supported SDG Goals
        </h2>

        <div className="grid md:grid-cols-5 gap-4">

          <div className="bg-yellow-500 p-4 rounded-xl text-center font-bold">
            SDG 7
          </div>

          <div className="bg-orange-500 p-4 rounded-xl text-center font-bold">
            SDG 11
          </div>

          <div className="bg-red-500 p-4 rounded-xl text-center font-bold">
            SDG 12
          </div>

          <div className="bg-green-600 p-4 rounded-xl text-center font-bold">
            SDG 13
          </div>

          <div className="bg-green-800 p-4 rounded-xl text-center font-bold">
            SDG 15
          </div>

        </div>

      </div>

    </div>

  );

}

export default Dashboard;