import { useState } from "react";

import jsPDF from "jspdf";

import { signOut } from "firebase/auth";

import { auth, db } from "../firebase";
import { motion } from "framer-motion";


import {
  PieChart,
  Pie,
  Cell,
  Tooltip,
  Legend
} from "recharts";

import {
  addDoc,
  collection
} from "firebase/firestore";

function Dashboard() {

  const [transport, setTransport] = useState("");
  const [electricity, setElectricity] = useState("");
  const [food, setFood] = useState("");

  const [darkMode, setDarkMode] = useState(true);

  // TOTAL

  const transportCO2 = Number(transport || 0) * 0.21;

  const electricityCO2 = Number(electricity || 0) * 0.82;

  const foodCO2 = Number(food || 0) * 0.0015;

 const total = Number(
  (
    transportCO2 +
    electricityCO2 +
    foodCO2
  ).toFixed(2)
);
const progress = Math.min((Number(total) / 200) * 100, 100);

    
  // CHART DATA


  const data = [
    {
      name: "Transport",
      value: Number(transport || 0)
    },
    {
      name: "Electricity",
      value: Number(electricity || 0)
    },
    {
      name: "Calories",
      value: Number(food || 0)
    }
  ];

  const COLORS = [
    "#22c55e",
    "#3b82f6",
    "#f97316"
  ];

  // ECO STATUS
let grade = "";
let badge = "";
let achievement = "";
let specialReward = "";

  if (total <= 50) {
    grade = "🌱 Excellent";
    badge = "🌱 Eco Hero";
    achievement = "🌱 Eco Warrior";
}
else if (total <= 100) {
    grade = "🌍 Moderate";
    badge = "🌍 Eco Supporter";
    achievement = "🌍 Green Supporter";
}
else {
    grade = "⚠️ High Emission";
    badge = "⚠️ Pollution Alert";
    achievement = "⚠️ Needs Improvement";
}

  // PDF DOWNLOAD

  const downloadPDF = () => {

    const doc = new jsPDF();

    doc.setFillColor(204, 232, 207);

    doc.rect(0, 0, 210, 297, "F");

    doc.setFontSize(24);

    doc.setTextColor(0, 128, 0);

    doc.text(
      "Eco Carbon Footprint Report",
      20,
      20
    );

    doc.setDrawColor(34, 197, 94);

    doc.line(20, 28, 190, 28);

    doc.setFontSize(18);

    doc.setTextColor(0, 0, 0);

    doc.text("Carbon Details", 20, 45);

    doc.setFontSize(15);

    doc.text(
      `Transport Value: ${transport || 0}`,
      25,
      65
    );

    doc.text(
      `Electricity Value: ${electricity || 0}`,
      25,
      85
    );

    doc.text(
      `Total Calories: ${total || 0} kcal`,
      25,
      105
    );

    doc.setFontSize(18);

    doc.setTextColor(220, 38, 38);

    doc.text(
      `Total CO2 Score: ${total}`,
      20,
      135
    );

    doc.setFontSize(16);

    doc.setTextColor(0, 0, 0);

    doc.text(
      `Achievement Badge: ${badge}`,
      20,
      160
    );

    const today = new Date();

    doc.setFontSize(12);

    doc.text(
      `Generated on: ${today.toLocaleString()}`,
      20,
      190
    );

    doc.setTextColor(100);

    doc.text(
      "Generated by Eco Carbon Tracker",
      20,
      270
    );

    doc.save("Eco_Report.pdf");

  };

  // SAVE REPORT

  const saveReport = async () => {
    try {

      console.log("Current User:", auth.currentUser);

      if (!auth.currentUser) {
        alert("User not logged in");
        return;
      }

      const report = {
        userId: auth.currentUser.uid,
        transport: Number(transport || 0),
        electricity: Number(electricity || 0),
        food: Number(food || 0),
        total: Number(total),
        createdAt: new Date(),
      };

      console.log(report);

      const docRef = await addDoc(collection(db, "reports"), report);

      console.log("Saved:", docRef.id);

      alert("Saved Successfully");

    } catch (error) {

      console.error(error);

      alert(error.code + "\n" + error.message);

    }
  };
  // LOGOUT

 const handleLogout = async () => {
  await signOut(auth);
};

return (

    <div
      className={`min-h-screen flex transition-all duration-500 ${darkMode
        ? "bg-gradient-to-br from-slate-900 via-slate-800 to-green-900 text-white"
        : "bg-gray-100 text-black"
        }`}
  
    >
      {/* SIDEBAR */}

      <div className="w-64 bg-slate-950 shadow-2xl p-6 min-h-screen">

        <h2 className="text-2xl font-bold text-green-400 mb-8">
          🌍 Eco Tracker
        </h2>

        <div className="space-y-4">

          <a
            href="/dashboard"
            className="block p-4 rounded-xl bg-green-600 hover:bg-green-700 transition"
          >
            📊 Dashboard
          </a>

          <a
            href="/history"
            className="block p-4 rounded-xl bg-blue-600 hover:bg-blue-700 transition"
          >
            📜 History
          </a>

          <button
            onClick={() => setDarkMode(!darkMode)}
            className="w-full text-left p-4 rounded-xl bg-yellow-600 hover:bg-yellow-700 transition"
          >
            {darkMode ? "☀️ Light Mode" : "🌙 Dark Mode"}
          </button>

          <button
            onClick={handleLogout}
            className="w-full text-left p-4 rounded-xl bg-red-600 hover:bg-red-700 transition"
          >
            🚪 Logout
          </button>

        </div>


      </div>
      {/* MAIN CONTENT */}

      <div className="flex-1 p-8">
        {/* HERO SECTION */}

        <div className="text-center mb-6">

          <h1 className="text-6xl md:text-5xl font-extrabold text-green-400">
            🌍 Eco Carbon Tracker
          </h1>

          <p className="text-xl text-gray-300 mt-4">
            Monitor • Analyze • Reduce
          </p>

          <p className="text-lg text-gray-400 mt-2">
            Track and reduce your environmental impact
          </p>

        </div>
        {/* WELCOME CARD */}

        <div className="bg-slate-800 rounded-3xl p-6 mb-8 shadow-xl border border-slate-700">
          <h2 className="text-2xl font-bold text-green-400">
            👋 Welcome Back
          </h2>

          <p className="text-gray-400 mt-2">
            Track your carbon footprint, monitor emissions, and contribute to sustainable development goals.
          </p>
        </div>


        {/* STATS */}

        <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-10">

          <div className="bg-gradient-to-r from-green-600 to-green-500 rounded-3xl p-6 shadow-xl">
            <p className="text-gray-400 text-lg">🌿 Total CO₂</p>
            <h2 className="text-5xl font-bold text-green-400 mt-2">
              {total}
            </h2>
          </div>

          <div className="bg-gradient-to-r from-blue-600 to-blue-500 rounded-3xl p-6 shadow-xl">
            <p className="text-gray-400 text-lg">🌳 Trees Needed</p>
            <h2 className="text-5xl font-bold text-blue-400 mt-2">
              {Math.ceil(total / 21)}
            </h2>
          </div>

          <div className="bg-gradient-to-r from-purple-600 to-purple-500 rounded-3xl p-6 shadow-xl">
            <p className="text-gray-400 text-lg">🏆 Eco Grade</p>
            <h2 className="text-3xl font-bold text-purple-400 mt-2">
              {grade}
            </h2>
          </div>

        </div>

        {/* INPUTS */}

        <div className="grid md:grid-cols-3 gap-6">

          {/* TRANSPORT */}

          <div
            className={`p-6 rounded-3xl shadow-2xl border-t-4 border-green-500 hover:scale-105 transition-all duration-300 ${darkMode
              ? "bg-slate-800/80 backdrop-blur-md"
              : "bg-white"
              }`}
          >
            <h2 className="text-2xl mb-4 text-green-400">
              🚗 Transport
            </h2>

            <input
              type="number"
              placeholder="KM traveled"
              value={transport}
              onChange={(e) =>
                setTransport(e.target.value)
              }
              className="w-full p-4 rounded-xl bg-slate-700 text-white border border-slate-600 focus:border-green-400 focus:ring-2 focus:ring-green-400 focus:outline-none"
            />
          </div>

          {/* ELECTRICITY */}

          <div
            className={`p-6 rounded-2xl shadow-lg ${darkMode
              ? "bg-slate-800/80 backdrop-blur-md"
              : "bg-white"
              }`}
          >
            <h2 className="text-2xl mb-4 text-yellow-500">
              ⚡ Electricity
            </h2>

            <input
              type="number"
              placeholder="Units consumed"
              value={electricity}
              onChange={(e) =>
                setElectricity(e.target.value)
              }
              className="w-full p-4 rounded-xl bg-slate-700 text-white border border-slate-600 focus:border-green-400 focus:ring-2 focus:ring-green-400 focus:outline-none"
            />
          </div>

          {/* FOOD */}

          <div
            className={`p-6 rounded-2xl shadow-lg ${darkMode
              ? "bg-slate-800/80 backdrop-blur-md"
              : "bg-white"
              }`}
          >
            <h2 className="text-2xl mb-4 text-red-500">
              🔥 Total Calories
            </h2>

            <input
              type="number"
              placeholder="Enter calories (kcal)"
              value={food}
              onChange={(e) => setFood(e.target.value)}
              className="w-full p-4 rounded-xl bg-slate-700 text-white border border-slate-600 focus:border-green-400 focus:ring-2 focus:ring-green-400 focus:outline-none"
            />
          </div>

        </div>

        <div className="mt-10 p-10 rounded-3xl text-center shadow-2xl bg-gradient-to-r from-green-600 to-emerald-700">

          <h2 className="text-4xl font-bold mb-4">
            Total Carbon Score
          </h2>

          <p className="text-6xl font-bold mb-4">
            {total} CO₂
          </p>

          <p className="text-2xl font-bold">
            {grade}
          </p>

          <p className="mt-4 text-xl font-semibold">
            🌳 Trees Needed to Offset:
            {" "}
            {Math.ceil(total / 10)}
          </p>

          <p className="mt-4 text-2xl font-bold">
            🏆 Badge: {badge}
          </p>

          <p className="mt-4 text-xl font-semibold">
            🎖 Achievement: {achievement}
          </p>

          {specialReward && (

            <p className="mt-4 text-2xl font-bold text-yellow-300">
              {specialReward}
            </p>

          )}

          {/* PROGRESS BAR */}

          <div className="mt-6">

            <p className="text-xl font-bold mb-2">
              Carbon Impact Level
            </p>
            <div className="bg-gray-700 rounded-full h-5 overflow-hidden">
              <div
                className={`h-5 rounded-full ${total <= 50
                    ? "bg-green-500"
                    : total <= 100
                      ? "bg-yellow-500"
                      : total <= 150
                        ? "bg-orange-500"
                        : "bg-red-500"
                  }`}
                style={{ width: `${progress}%` }}
              />
            </div>

          </div>

        </div>

        {/* BUTTONS */}

       <div className="flex gap-4 justify-center mt-6">

         <button ...>
           Save Report
         </button>

        <button ...>
          Download PDF
        </button>

       </div>

       </div>  

        

      

      {/* RECOMMENDATIONS */}

      <div
        className={`mt-10 p-8 rounded-2xl ${darkMode
          ? "bg-slate-800/80 backdrop-blur-md"
          : "bg-green-50"
          }`}
      >

        <h2 className="text-3xl mb-6 text-green-400">
          💡 Smart Eco Recommendations
        </h2>

        <ul className="space-y-4 text-lg">

          {transport > 100 && (
            <li>
              🚲 Use public transport or cycling.
            </li>
          )}

          {electricity > 100 && (
            <li>
              💡 Reduce electricity usage.
            </li>
          )}

          {food > 50 && (
            <li>
             🔥 Reduce excessive calorie intake and avoid food waste. 
            </li>
          )}

          {total < 150 && (
            <li>
              🌱 Great job! Low carbon footprint.
            </li>
          )}

        </ul>

      </div>

      {/* CHART */}

      <div
        className={`mt-10 p-8 rounded-2xl ${darkMode
          ? "bg-slate-800/80 backdrop-blur-md"
          : "bg-blue-50"
          }`}
      >

        <h2 className="text-3xl mb-6 text-center text-green-400">
          📊 Emission Analytics
        </h2>

        <div className="flex justify-center">

          <PieChart width={400} height={400}>

            <Pie
              data={data}
              cx="50%"
              cy="50%"
              outerRadius={120}
              dataKey="value"
              label
            >

              {data.map((entry, index) => (

                <Cell
                  key={index}
                  fill={COLORS[index]}
                />

              ))}

            </Pie>

            <Tooltip />

            <Legend />

          </PieChart>

        </div>

      </div>
    </div>

    

  );

}

export default Dashboard;